### ISSUE TITLE
TypeError exception during initialisation

### ISSUE THREAD

**Issue by rieck** [zackwag/homebridge-somneo#32]
First of all, thanks for writing this plugin! 

**Describe The Bug:**

The plugin causes a `TypeError` during initialisation. The exception looks like this:

```
[11/09/2021, 17:03:49] [somneo platform] Initializing HomebridgeSomneo platform...
[11/09/2021, 17:03:49] TypeError: this.temperatureService.getCharacteristic(...).onSet is not a function
    at new SomneoSensorAccessory (/usr/local/lib/node_modules/homebridge-somneo/src/lib/somneoSensorAccessory.ts:30:8)
    at SomneoPlatform.buildAccessories (/usr/local/lib/node_modules/homebridge-somneo/src/somneoPlatform.ts:55:33)
    at new SomneoPlatform (/usr/local/lib/node_modules/homebridge-somneo/src/somneoPlatform.ts:40:10)
    at /usr/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**To Reproduce:**

I guess my installation is broken, otherwise this would have popped up earlier. I am using the following components: 

```
── homebridge@1.3.4
── homebridge-somneo@1.6.0
── npm@7.23.0
```

**Expected behavior:**

No exception. 

**Logs:**

```
[11/09/2021, 17:11:27] Loading 2 platforms...
[11/09/2021, 17:11:27] [netatmo platform] Initializing netatmo platform...
[11/09/2021, 17:11:27] [somneo platform] Initializing HomebridgeSomneo platform...
[11/09/2021, 17:11:27] TypeError: this.temperatureService.getCharacteristic(...).onSet is not a function
    at new SomneoSensorAccessory (/usr/local/lib/node_modules/homebridge-somneo/src/lib/somneoSensorAccessory.ts:30:8)
    at SomneoPlatform.buildAccessories (/usr/local/lib/node_modules/homebridge-somneo/src/somneoPlatform.ts:55:33)
    at new SomneoPlatform (/usr/local/lib/node_modules/homebridge-somneo/src/somneoPlatform.ts:40:10)
    at /usr/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
[11/09/2021, 17:11:27] Got SIGTERM, shutting down Homebridge...
```

**Plugin Config:**

```json
    {
       "platform": "HomebridgeSomneo",
       "name": "somneo platform",
       "somneos": [
         {
           "name": "Somneo",
           "host": "192.168.178.101"
         }
       ]
    }
```

**Environment:**

* **Plugin Version**: 1.6.0
* **Homebridge Version**: 1.3.4
* **Node.js Version**: 14.15.3
* **NPM Version**: 7.23.0
* **Operating System**: Raspbian

**Comment by zackwag** [comment]
Thanks for the detailed report, and sorry for the long silence.

Looking into this now: the crash site is unchanged in current code and still calls `Characteristic.onSet()`/`.onGet()`, an API introduced in **Homebridge 1.3.0** (HAP-NodeJS 0.9.0). You reported running Homebridge 1.3.4, which should have had that method available — so this doesn't look like a bug in the plugin's logic itself, but rather an npm/hap-nodejs dependency-resolution issue specific to your environment at the time (npm 7's hoisting had known problems right around when this HAP-NodeJS API shipped in mid-2021, and several plugins saw a wave of near-identical reports).

One real bug I did find while investigating: `engines.homebridge` in `package.json` had always incorrectly said `">=1.0.0"`, two minor versions below what the plugin actually requires. That's fixed in #59 — it won't retroactively help this specific 2021 report, but it means a genuinely incompatible Homebridge install now gets an npm engine warning instead of this same cryptic `TypeError`.

Closing as stale/environmental given there's been no reproduction in ~5 years and current Homebridge/npm versions no longer have the hoisting issues from that era. Please reopen if you're still able to reproduce this on a current setup.
