### ISSUE TITLE
Can't make it work - have Somneo model HF3672/01.

### ISSUE THREAD

**Issue by MaltefromFB** [zackwag/homebridge-somneo#35]
Hey man,

Thanks so much for creating this plugin.

I am having some issues with it though. Could you have a look at the error code to see what might be wrong? Would be much appraciated!

[02/06/2022, 21:58:14] TypeError: this.getBinaryService(...).getCharacteristic(...).onSet is not a function
at new SomneoSwitchAccessory (/usr/local/lib/node_modules/homebridge-somneo/src/lib/somneoSwitchAccessory.ts:21:8)
at new SomneoSunsetSwitchAccessory (/usr/local/lib/node_modules/homebridge-somneo/src/lib/somneoSunsetSwitchAccessory.ts:4:1)
at SomneoPlatform.buildAccessories (/usr/local/lib/node_modules/homebridge-somneo/src/somneoPlatform.ts:91:30)
at new SomneoPlatform (/usr/local/lib/node_modules/homebridge-somneo/src/somneoPlatform.ts:40:10)
at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
at Array.forEach (<anonymous>)
at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

**Comment by zackwag** [comment]
Can you post your platform configuration?

**Comment by MaltefromFB** [comment]
{
    "bridge": {
        "name": "XX",
        "username": "XX",
        "port": XX,
        "pin": "XX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "ADAX",
            "clientId": "XX",
            "secret": "XX",
            "maxPollInterval": 60,
            "platform": "ADAX"
        },
        {
            "name": "Homebridge Somneo",
            "somneos": [
                {
                    "name": "Somneo",
                    "host": "192.168.0.10",
                    "sensors": {
                        "humidity": {
                            "isEnabled": true
                        },
                        "lux": {
                            "isEnabled": true
                        },
                        "temperature": {
                            "isEnabled": true
                        }
                    },
                    "lights": {
                        "mainLight": {
                            "isEnabled": true
                        },
                        "nightLight": {
                            "isEnabled": true
                        }
                    },
                    "switches": {
                        "relaxBreathe": {
                            "isEnabled": true,
                            "breathsPerMin": 4,
                            "duration": 10,
                            "guidanceType": 0,
                            "lightIntensity": 80,
                            "volume": 48
                        },
                        "sunset": {
                            "isEnabled": true,
                            "duration": 30,
                            "lightIntensity": 80,
                            "colorScheme": 0,
                            "ambientSounds": "1",
                            "volume": 48
                        }
                    },
                    "audio": {
                        "isEnabled": true,
                        "favoriteInput": 1
                    }
                }
            ],
            "platform": "HomebridgeSomneo"
        }
    ]
}

**Comment by MaltefromFB** [comment]
Hope this is the config you were looking for. I am an absolute noob, so please let me know if this was not it.
Also FYI, I've replaced some username and password in there with "XX".

Thank you so much for having a look!

**Comment by MaltefromFB** [comment]
Oh and FYI, I am using Homebridge GUI for setup and install.

**Comment by zackwag** [comment]
Circling back on this one — sorry it sat so long.

This is the same underlying issue as #32: `TypeError: ...onSet is not a function` during platform init. That API (`Characteristic.onSet`/`.onGet`) was introduced in **Homebridge 1.3.0**, and it's used throughout this plugin (every accessory type, including the sunset switch in your stack trace). At the time this was reported, `engines.homebridge` in `package.json` incorrectly allowed `>=1.0.0`, so npm wouldn't warn on install against an incompatible (pre-1.3.0) Homebridge version — it would just crash with this same cryptic error.

That's now fixed (see #32 and #59): `engines.homebridge` correctly requires `>=1.3.0`.

Closing as a duplicate of #32. If you're still hitting this on a current Homebridge/plugin version, please reopen with your `homebridge -V` output and I'll take another look.
